# Generated by Django 2.2.7 on 2019-11-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20191124_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='url',
            new_name='url_order',
        ),
    ]
